/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto-ota.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto-ota.pb-c.h"
void   firm_update_start__init
                     (FirmUpdateStart         *message)
{
  static const FirmUpdateStart init_value = FIRM_UPDATE_START__INIT;
  *message = init_value;
}
size_t firm_update_start__get_packed_size
                     (const FirmUpdateStart *message)
{
  assert(message->base.descriptor == &firm_update_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t firm_update_start__pack
                     (const FirmUpdateStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &firm_update_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t firm_update_start__pack_to_buffer
                     (const FirmUpdateStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &firm_update_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FirmUpdateStart *
       firm_update_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FirmUpdateStart *)
     protobuf_c_message_unpack (&firm_update_start__descriptor,
                                allocator, len, data);
}
void   firm_update_start__free_unpacked
                     (FirmUpdateStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &firm_update_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   firm_pkt_req__init
                     (FirmPktReq         *message)
{
  static const FirmPktReq init_value = FIRM_PKT_REQ__INIT;
  *message = init_value;
}
size_t firm_pkt_req__get_packed_size
                     (const FirmPktReq *message)
{
  assert(message->base.descriptor == &firm_pkt_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t firm_pkt_req__pack
                     (const FirmPktReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &firm_pkt_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t firm_pkt_req__pack_to_buffer
                     (const FirmPktReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &firm_pkt_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FirmPktReq *
       firm_pkt_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FirmPktReq *)
     protobuf_c_message_unpack (&firm_pkt_req__descriptor,
                                allocator, len, data);
}
void   firm_pkt_req__free_unpacked
                     (FirmPktReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &firm_pkt_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   firm_pkt_res__init
                     (FirmPktRes         *message)
{
  static const FirmPktRes init_value = FIRM_PKT_RES__INIT;
  *message = init_value;
}
size_t firm_pkt_res__get_packed_size
                     (const FirmPktRes *message)
{
  assert(message->base.descriptor == &firm_pkt_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t firm_pkt_res__pack
                     (const FirmPktRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &firm_pkt_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t firm_pkt_res__pack_to_buffer
                     (const FirmPktRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &firm_pkt_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FirmPktRes *
       firm_pkt_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FirmPktRes *)
     protobuf_c_message_unpack (&firm_pkt_res__descriptor,
                                allocator, len, data);
}
void   firm_pkt_res__free_unpacked
                     (FirmPktRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &firm_pkt_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor firm_update_start__field_descriptors[1] =
{
  {
    "image_size",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(FirmUpdateStart, has_image_size),
    offsetof(FirmUpdateStart, image_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned firm_update_start__field_indices_by_name[] = {
  0,   /* field[0] = image_size */
};
static const ProtobufCIntRange firm_update_start__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor firm_update_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FirmUpdateStart",
  "FirmUpdateStart",
  "FirmUpdateStart",
  "",
  sizeof(FirmUpdateStart),
  1,
  firm_update_start__field_descriptors,
  firm_update_start__field_indices_by_name,
  1,  firm_update_start__number_ranges,
  (ProtobufCMessageInit) firm_update_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor firm_pkt_req__field_descriptors[2] =
{
  {
    "numBytes",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(FirmPktReq, has_numbytes),
    offsetof(FirmPktReq, numbytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "advanceAddress",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(FirmPktReq, has_advanceaddress),
    offsetof(FirmPktReq, advanceaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned firm_pkt_req__field_indices_by_name[] = {
  1,   /* field[1] = advanceAddress */
  0,   /* field[0] = numBytes */
};
static const ProtobufCIntRange firm_pkt_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor firm_pkt_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FirmPktReq",
  "FirmPktReq",
  "FirmPktReq",
  "",
  sizeof(FirmPktReq),
  2,
  firm_pkt_req__field_descriptors,
  firm_pkt_req__field_indices_by_name,
  1,  firm_pkt_req__number_ranges,
  (ProtobufCMessageInit) firm_pkt_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor firm_pkt_res__field_descriptors[1] =
{
  {
    "pkt",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(FirmPktRes, n_pkt),
    offsetof(FirmPktRes, pkt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned firm_pkt_res__field_indices_by_name[] = {
  0,   /* field[0] = pkt */
};
static const ProtobufCIntRange firm_pkt_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor firm_pkt_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FirmPktRes",
  "FirmPktRes",
  "FirmPktRes",
  "",
  sizeof(FirmPktRes),
  1,
  firm_pkt_res__field_descriptors,
  firm_pkt_res__field_indices_by_name,
  1,  firm_pkt_res__number_ranges,
  (ProtobufCMessageInit) firm_pkt_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
