# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto-ota.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto-ota.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fproto-ota.proto\"%\n\x0f\x46irmUpdateStart\x12\x12\n\nimage_size\x18\x01 \x01(\x05\"6\n\nFirmPktReq\x12\x10\n\x08numBytes\x18\x01 \x01(\x05\x12\x16\n\x0e\x61\x64vanceAddress\x18\x02 \x01(\x08\"\x19\n\nFirmPktRes\x12\x0b\n\x03pkt\x18\x01 \x03(\x0c'
)




_FIRMUPDATESTART = _descriptor.Descriptor(
  name='FirmUpdateStart',
  full_name='FirmUpdateStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_size', full_name='FirmUpdateStart.image_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=56,
)


_FIRMPKTREQ = _descriptor.Descriptor(
  name='FirmPktReq',
  full_name='FirmPktReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='numBytes', full_name='FirmPktReq.numBytes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='advanceAddress', full_name='FirmPktReq.advanceAddress', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=112,
)


_FIRMPKTRES = _descriptor.Descriptor(
  name='FirmPktRes',
  full_name='FirmPktRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pkt', full_name='FirmPktRes.pkt', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['FirmUpdateStart'] = _FIRMUPDATESTART
DESCRIPTOR.message_types_by_name['FirmPktReq'] = _FIRMPKTREQ
DESCRIPTOR.message_types_by_name['FirmPktRes'] = _FIRMPKTRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FirmUpdateStart = _reflection.GeneratedProtocolMessageType('FirmUpdateStart', (_message.Message,), {
  'DESCRIPTOR' : _FIRMUPDATESTART,
  '__module__' : 'proto_ota_pb2'
  # @@protoc_insertion_point(class_scope:FirmUpdateStart)
  })
_sym_db.RegisterMessage(FirmUpdateStart)

FirmPktReq = _reflection.GeneratedProtocolMessageType('FirmPktReq', (_message.Message,), {
  'DESCRIPTOR' : _FIRMPKTREQ,
  '__module__' : 'proto_ota_pb2'
  # @@protoc_insertion_point(class_scope:FirmPktReq)
  })
_sym_db.RegisterMessage(FirmPktReq)

FirmPktRes = _reflection.GeneratedProtocolMessageType('FirmPktRes', (_message.Message,), {
  'DESCRIPTOR' : _FIRMPKTRES,
  '__module__' : 'proto_ota_pb2'
  # @@protoc_insertion_point(class_scope:FirmPktRes)
  })
_sym_db.RegisterMessage(FirmPktRes)


# @@protoc_insertion_point(module_scope)
